[pytest]
testpaths = tests
pythonpath = .
python_files = test_*.py
python_classes = Test*
python_functions = test_*
filterwarnings =
    ignore:.*on_event is deprecated.*:DeprecationWarning
    ignore::DeprecationWarning:fastapi.*
    ignore::DeprecationWarning:starlette.*
